apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend
  namespace: production
spec:
  ingressClassName: alb
  rules:
    - host: api.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 3000
